#pull base image
FROM openjdk:8-jdk-alpine

#maintainer 
MAINTAINER dstar55@yahoo.com

#default command
CMD java -jar /data/consumer-0.1.0.jar

#copy hello world to docker image
ADD ./data/consumer-0.1.0.jar /data/consumer-0.1.0.jar
